### ISSUE TITLE
Firmware To-Do Items

### ISSUE THREAD

**Issue by hedgecrw** [vu-a3em/a3em-firmware#1]
- [ ] Extend audio clip if constant sound detected
- [x] Discard first IMU sample after wake-up
- [ ] Figure out why VCOMP doesn't work with external ref voltage
- [x] Experiment with XT-based timers for audio sample rate to increase accuracy
- [ ] Integrate exFAT formatting into dashboard
- [x] Parse log files to get statistics (add to dashboard)
